name: "📚 Сдача задания"
description: "Отправка выполненного домашнего задания студентом"
title: "[СДАЧА]: "
labels: ["submission", "требует проверки"]
assignees: virusneo1997-del
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за выполнение задания! Пожалуйста, заполни форму ниже.
  - type: input
    id: name
    attributes:
      label: "ФИО"
      description: "Ваше полное имя"
      placeholder: "Иванов Иван Иванович"
    validations:
      required: true
  - type: input
    id: group
    attributes:
      label: "Группа"
      placeholder: "ИТ-21"
    validations:
      required: true
  - type: dropdown
    id: lesson
    attributes:
      label: "Номер урока"
      description: "Выберите урок, задание по которому вы сдаете"
      options:
        - Урок 1: Установка Ubuntu Server
        - Урок 2: Пользователи и права доступа
        - Урок 3: Веб-сервер Nginx
        - Урок 4: Мониторинг системы
    validations:
      required: true
  - type: checkboxes
    id: tasks
    attributes:
      label: "Выполненные задачи"
      description: "Отметьте пункты, которые вы выполнили"
      options:
        - label: Основное задание урока
        - label: Дополнительные задачи
        - label: Ответил на контрольные вопросы
  - type: textarea
    id: comments
    attributes:
      label: "Комментарии и вопросы"
      description: "Опишите трудности, с которыми столкнулись, или задайте вопросы преподавателю."
      placeholder: "На этом этапе у меня возникла проблема..."
  - type: markdown
    attributes:
      value: |
        Не забудьте прикрепить файлы вашего решения (скриншоты, код, отчеты) ниже.